# Etiquetas para variables numéricas del matched
var_labels <- list(
  numero_de_mujeres_organizacion_pct = "% Women in Organization",
  mujeres_transgenero_pct = "% Transgender Women",
  otro_genero_pct = "% Other Gender",
  mujeres_transgenero_pc = "% Transgender Women (alt)",
  total_personas = "Total Persons",
  orientacion_sexual_hetero_pct = "% Heterosexual Orientation",
  orientacion_gay_pct = "% Gay Orientation",
  orientacion_bisexual_pct = "% Bisexual Orientation",
  orientacion_otro_pct = "% Other Sexual Orientation",
  orientacion_no_informa_pct = "% No Info Sexual Orientation",
  personas_entre_los_18_28_anos_pct = "% Aged 18-28",
  personas_mayores_de_60_anos_pct = "% Aged 60+",
  indigenas_pct = "% Indigenous",
  rrom_pct = "% Rrom",
  raizales_pct = "% Raizales",
  palenqueras_pct = "% Palenqueras",
  negras_afrocolombianas_pct = "% Black/Afrocolombian",
  sin_reconocimiento_etnico_pct = "% No Ethnic Recognition",
  size_etnia_total_pct = "% Total Ethnic Size",
  personas_sisben_a_pct = "% SISBEN A",
  personas_sisben_b_pct = "% SISBEN B",
  personas_sisben_c_pct = "% SISBEN C",
  persona_sisben_d_pct = "% SISBEN D",
  personas_reincroporadas_pct = "% Reincorporated",
  personas_lideres_pct = "% Leaders",
  victimas_pct = "% Victims"
)
